export const ADD_FAVORITES = "ADD_FAVORITES";
export const DELETE_FAVORITES = "DELETE_FAVORITES";

export const GET_RECIPES = "GET_RECIPES";
export const SORT_RECIPES = "SORT_RECIPES";
export const SEARCH_RECIPES = "SEARCH_RECIPES";
